name: "Copy to S3 Bucket"
description: "Sync a local directory to a bucket"
inputs:
  github_iam_role:
    description: Name of the IAM Role for syncing files to the S3 Bucket, needs write access
  aws_account_id:
    description: AWS Account ID
  aws_region:
    description: Target AWS Region
    default: "eu-central-1"
  bucket_id:
    description: Bucket id
  source_dir:
    description: Source directory to sync to S3
    default: "dist/"
  destination_dir:
    description: Destination directory to sync to in S3
    default: ""
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ inputs.github_iam_role }}
        aws-region: ${{ inputs.aws_region }}

    - name: Upload files to S3 bucket
      id: sync
      shell: bash
      run: aws s3 sync "${{ inputs.source_dir }}" "s3://${{ inputs.bucket_id }}/${{ inputs.destination_dir }}"
