name: Determine Service Data
description: Extract service data from input
inputs:
  service:
    description: Service name
    required: true
  path:
    description: Service path
    required: true
outputs:
  image_name:
    description: Image Name
    value: "${{ steps.build-data.outputs.image_name }}"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Collect Data
      id: build-data
      shell: bash
      run: |
        set -eux
        BUILD="{}"
        if [ -f "${{ input.path }}/build.yaml" ]; then
            BUILD=$(yq -o json "${{ input.path }}/build.yaml" | jq -c)
        fi
        echo 'Build Data:'
        jq 'if (has("image_name") | not) then (. + {image_name: "${{ input.service }}"}) else . end' <<< "$BUILD"
        jq -r 'if (has("image_name") | not) then (. + {image_name: "${{ input.service }}"}) else . end | to_entries[] | "\(.key)=\(.value)"' <<< "$BUILD" >> $GITHUB_OUTPUT
