name: "Build image"
description: "Docker image build and publish"
inputs:
  backend_iam_role:
    description: Name of the Terraform backend assumable IAM Role
    default: "github-actions_terraform-backend"
  aws_account_id:
    description: AWS Account ID
  aws_region:
    description: Target AWS Region
    default: "eu-central-1"
  q_service:
    description: Quinyx Service, like 'qwfmbackend' or 'security'
  function_image:
    description: Docker image
  tags:
    description: Tags to add to the function
  environment:
    description: Environment
  name:
    description: name after service
  description:
    description: description of the function
  environment_variables:
    description: environment variables
    default: "{}"
  architectures:
    description: Instruction set architecture for your Lambda function. Valid values are ['x86_64'] and ['arm64'].
    default: '["arm64"]'
  vpc:
    description: whether this function should live within the vpc
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Manage Lambda
      uses: quinyx-tjeerd/actions/terraform-automated@main
      env:
        TF_VAR_region: ${{ inputs.aws_region }}
        TF_VAR_tags: ${{ inputs.tags }}
        TF_VAR_environment: ${{ inputs.environment }}
        TF_VAR_service: ${{ inputs.q_service }}
        TF_VAR_name: ${{ inputs.name }}
        TF_VAR_description: ${{ inputs.description }}
        TF_VAR_environment_variables: ${{ inputs.environment_variables }}
        TF_VAR_architectures: ${{ inputs.architectures }}
        TF_VAR_vpc: ${{ inputs.vpc == 'true' }}
        TF_VAR_image: ${{ inputs.function_image }}
      with:
        backend_iam_role: ${{ inputs.backend_iam_role }}
        aws_account_id: ${{ inputs.aws_account_id }}
        aws_region: ${{ inputs.aws_region }}
        aws_service: Lambda
        q_service: ${{ inputs.image_name}}
        working-directory: ${{ github.action_path }}
