name: "Build image"
description: "Docker image build and publish"
inputs:
  aws_account_id:
    description: AWS Account ID
    default: "488021763009"
  aws_region:
    description: Target AWS Region
    default: "eu-central-1"
  github_iam_role_arn:
    description: Name of the IAM Role for managing IAM Roles, also needs to assume the terraform role
    default: "arn:aws:iam::488021763009:role/github-actions_iam-roles"
  roles_yaml:
    description: Path to Yaml file containing the role definitions
  backend_iam_role:
    description: Name of the Terraform backend assumable IAM Role
    default: "github-actions_terraform-backend"
  q_service:
    description: Quinyx service name
  tags:
    description: Tags
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.github_iam_role_arn }}
        aws-region: ${{ inputs.aws_region }}
    - name: Input roles
      shell: bash
      run: echo roles-input ${{ inputs.roles_yaml }}
    - name: Manage IAM Roles
      uses: quinyx-tjeerd/actions/terraform-automated@main
      env:
        TF_VAR_aws_account_id: ${{ inputs.aws_account_id }}
        TF_VAR_roles_yaml: ${{ inputs.roles_yaml }}
        TF_VAR_tags: ${{ inputs.tags }}

      with:
        aws_region: ${{ inputs.aws_region }}
        aws_service: IAM-Roles
        tf_state_prefix: ${{ format( "{0}{1}", inputs.q_service, (inputs.component != '' && format('/{0}', inputs.component) || '')) }}
        working-directory: ${{ github.action_path }}
