name: "Manage S3 Bucket"
description: "Create and manage a bucket using terraform"
inputs:
  backend_iam_role:
    description: Name of the Terraform backend assumable IAM Role
    default: "github-actions_terraform-backend"
  github_iam_role:
    description: Name of the IAM Role for managing the S3 Bucket, also needs to assume the terraform role
    default: "github-actions_s3-bucket"
  aws_account_id:
    description: AWS Account ID
  aws_region:
    description: Target AWS Region
    default: "eu-central-1"
  q_service:
    description: Quinyx Service, like 'qwfmbackend' or 'security'
  tags:
    description: Tags to add to the bucket
  environment:
    description: Environment
  component:
    description: Component of service, like a sub division
    default: ""
  description:
    description: description of the bucket
    default: ""
  custom_name:
    description: custom name for the bucket
    default: ""
  versioning:
    description: Enable object versioning
    default: "true"
  kms_key_arn:
    description: Use KMS encryption with specified key
    default: ""
  lifecycle_rules:
    description: Lifecycle rules, list of objects [ {rule} ]
    default: "[]"
  allowed_users:
    description: List of IAM users
    default: "[]"
  allowed_groups:
    description: List of IAM groups
    default: "[]"
  allowed_roles:
    description: List of IAM roles
    default: "[]"
outputs:
  json:
    description: "JSON"
    value: ${{ steps.terraform.outputs.json }}
  bucket_arn:
    description: "S3 Bucket ARN"
    value: ${{ steps.terraform.outputs.bucket_arn }}
  bucket_id:
    description: "S3 Bucket ID"
    value: ${{ steps.terraform.outputs.bucket_id }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ inputs.github_iam_role }}
        aws-region: ${{ inputs.aws_region }}

    - id: terraform
      name: Manage S3 bucket
      uses: quinyx-tjeerd/actions/terraform-automated@main
      env:
        TF_VAR_region: ${{ inputs.aws_region }}
        TF_VAR_environment: ${{ inputs.environment }}
        TF_VAR_service: ${{ inputs.q_service }}
        TF_VAR_tags: ${{ inputs.tags }}
        TF_VAR_component: ${{ inputs.component }}
        TF_VAR_description: ${{ inputs.description }}
        TF_VAR_custom_name: ${{ inputs.custom_name }}
        TF_VAR_versioning: ${{ inputs.versioning == 'true' }}
        TF_VAR_lifecycle_rules: ${{ inputs.lifecycle_rules }}
        TF_VAR_allowed_users: ${{ inputs.allowed_users }}
        TF_VAR_allowed_groups: ${{ inputs.allowed_groups }}
        TF_VAR_allowed_roles: ${{ inputs.allowed_roles }}
      with:
        backend_iam_role: ${{ inputs.backend_iam_role }}
        aws_account_id: ${{ inputs.aws_account_id }}
        aws_region: ${{ inputs.aws_region }}
        aws_service: S3
        q_service: ${{ inputs.q_service }}
        q_component: ${{ inputs.component }}
        q_environment: ${{ inputs.component }}
        working-directory: ${{ github.action_path }}

    - shell: bash
      run: |
        echo "${{ steps.terraform.outputs.json }}" | jq -c 'to_entries | .[] | "\(.key)=\(.value)"' | while read var; do
            echo "$var" >> "$GITHUB_OUTPUT"
        done
        echo JSON ${{ steps.terraform.outputs.json }}
        echo ARN ${{ steps.terraform.outputs.bucket_arn }}
        echo ID ${{ steps.terraform.outputs.bucket_id }}
